theme: jekyll-theme-midnight
title: Silly little blog
author: Beckham C.
email: beckhamjcarver@gmail.com

description: >
  A foray into both GitHub pages and putting my game design/crique
  ideas to paper- cloud hosted strings.
  
 github_username: beckcarver
 
 show_excerpts: false
